version: 2
general:
    branches:
        only:
            - gh-pages
jobs:
    build:
        docker:
            - image: circleci/golang:1.8
        working_directory: /go/src/github.com/istanbul-coders/istanbul-coders
        steps:
            - checkout
            - run:
                name: Get monsterghost
                command: go get github.com/istanbul-coders/monsterghost
            - run:
                name: Install pandoc
                command: sudo apt-get update && sudo apt-get install -y pandoc
            - run:
                name: Find latest event
                command: |
                    cat _posts/`ls _posts | sort | tail -1` > event.md
                    cat event.md
            - run:
                name: Parse latest event details
                command: |
                    echo `grep date event.md | cut -d" " -f2-7` > eventdate.md
                    echo `grep speaker event.md | cut -d" " -f2-5 |head -1` > speaker.md
                    echo `grep speaker-twitter event.md | cut -d" " -f2-10 |head -1`  > speakertwitter.md
                    echo `grep speaker-photo event.md | cut -d" " -f2-5 |head -1` > speakerphoto.md
                    echo `grep venue event.md | cut -d" " -f2-20 |head -1` > venue.md
                    echo `grep title event.md | cut -d" " -f2-30 |head -1`  > title.md
                    cat event.md
                    cat event.md| tail -n +12 > desc.md
                    pandoc -f markdown desc.md > desc.html
                    cat desc.html
            - run:
                name: Post to meetup.com
                command: |
                    desc=`cat desc.html`
                    name=`cat title.md`
                    time=`cat eventdate.md`
                    ./monsterghost meetup -desc "$desc" -apikey "${meetup_apikey}" -gid "${meetup_group_id}" -vid "${meetup_venue_id}" -name "$name" -rsvp_limit ${meetup_rsvp_limit} -time "$time"
            - run:
                name: Tweet
                command: |
                    eventdate=`cat eventdate.md`
                    speaker=`cat speaker.md`
                    speakertwitter=`cat speakertwitter.md`
                    speakerphoto=`cat speakerphoto.md`
                    venue=`cat venue.md`
                    title=`cat title.md`
                    desc=`cat desc.md`
                    url=`cat eventurl.md`
                    echo $url
                    subject="$title ($eventdate) @$speakertwitter $url"
                    echo $subject
                    monsterghost twitter -ckey ${ckey} -csecret ${csecret} -atoken ${atoken} -asecret ${asecret} -subject "$subject"
            - run:
                name: E-Mail to group
                command: |
                    body=`cat desc.md`
                    subject=`cat title.md`
                    subject=$subject" ( "`cat eventdate.md`" )"
                    monsterghost gmail -to "${to}" -from "abdulkadiryaman@gmail.com" -subject "Test Email" -body "Test Email" -username "${username}" -password "${password}"
